### ISSUE TITLE
No devices found (kinect works w freenect-glview)

### ISSUE THREAD

**Issue by jacksonkr** [felixendres/rgbdslam_v2#26]
rgbdslam worked fine on precise. I upgraded to trusty, installed ros indigo, and have everything working fine except that the camera isn't detected. You can see the output below.

```
$ roslaunch rgbdslam openni+rgbdslam.launch 
... logging to /home/jackson/.ros/log/41df8eaa-c913-11e5-be97-b886879b31ee/roslaunch-jackson-HP-Pavilion-Notebook-22023.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://jackson-HP-Pavilion-Notebook:52593/

SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/depth_rectify_depth/interpolation: 0
 * /camera/depth_registered_rectify_depth/interpolation: 0
 * /camera/disparity_depth/max_range: 4.0
 * /camera/disparity_depth/min_range: 0.5
 * /camera/disparity_registered_hw/max_range: 4.0
 * /camera/disparity_registered_hw/min_range: 0.5
 * /camera/disparity_registered_sw/max_range: 4.0
 * /camera/disparity_registered_sw/min_range: 0.5
 * /camera/driver/depth_camera_info_url: 
 * /camera/driver/depth_frame_id: camera_depth_opti...
 * /camera/driver/depth_registration: False
 * /camera/driver/device_id: #1
 * /camera/driver/rgb_camera_info_url: 
 * /camera/driver/rgb_frame_id: camera_rgb_optica...
 * /rgbdslam/config/backend_solver: pcg
 * /rgbdslam/config/cloud_creation_skip_step: 2
 * /rgbdslam/config/cloud_display_type: POINTS
 * /rgbdslam/config/detector_grid_resolution: 3
 * /rgbdslam/config/feature_detector_type: ORB
 * /rgbdslam/config/feature_extractor_type: ORB
 * /rgbdslam/config/max_keypoints: 600
 * /rgbdslam/config/max_matches: 300
 * /rgbdslam/config/min_sampled_candidates: 4
 * /rgbdslam/config/neighbor_candidates: 4
 * /rgbdslam/config/optimizer_skip_step: 1
 * /rgbdslam/config/pose_relative_to: largest_loop
 * /rgbdslam/config/predecessor_candidates: 4
 * /rgbdslam/config/ransac_iterations: 100
 * /rgbdslam/config/topic_image_depth: /camera/depth_reg...
 * /rgbdslam/config/topic_image_mono: /camera/rgb/image...
 * /rosdistro: indigo
 * /rosversion: 1.11.16

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    debayer (nodelet/nodelet)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_hw_metric_rect (nodelet/nodelet)
    depth_registered_metric (nodelet/nodelet)
    depth_registered_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    disparity_depth (nodelet/nodelet)
    disparity_registered_hw (nodelet/nodelet)
    disparity_registered_sw (nodelet/nodelet)
    driver (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    rectify_color (nodelet/nodelet)
    rectify_ir (nodelet/nodelet)
    rectify_mono (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
  /
    camera_base_link (tf/static_transform_publisher)
    camera_base_link1 (tf/static_transform_publisher)
    camera_base_link2 (tf/static_transform_publisher)
    camera_base_link3 (tf/static_transform_publisher)
    rgbdslam (rgbdslam/rgbdslam)

auto-starting new master
process[master]: started with pid [22036]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 41df8eaa-c913-11e5-be97-b886879b31ee
process[rosout-1]: started with pid [22049]
started core service [/rosout]
process[camera/camera_nodelet_manager-2]: started with pid [22066]
process[camera/driver-3]: started with pid [22067]
process[camera/debayer-4]: started with pid [22068]
process[camera/rectify_mono-5]: started with pid [22069]
process[camera/rectify_color-6]: started with pid [22079]
process[camera/rectify_ir-7]: started with pid [22091]
process[camera/depth_rectify_depth-8]: started with pid [22103]
[ INFO] [1454352026.660961647]: Initializing nodelet with 4 worker threads.
process[camera/depth_metric_rect-9]: started with pid [22117]
process[camera/depth_metric-10]: started with pid [22121]
process[camera/depth_points-11]: started with pid [22131]
process[camera/register_depth_rgb-12]: started with pid [22149]
process[camera/points_xyzrgb_sw_registered-13]: started with pid [22156]
process[camera/depth_registered_sw_metric_rect-14]: started with pid [22165]
process[camera/depth_registered_rectify_depth-15]: started with pid [22179]
process[camera/points_xyzrgb_hw_registered-16]: started with pid [22200]
process[camera/depth_registered_hw_metric_rect-17]: started with pid [22208]
process[camera/depth_registered_metric-18]: started with pid [22217]
process[camera/disparity_depth-19]: started with pid [22233]
process[camera/disparity_registered_sw-20]: started with pid [22236]
[ INFO] [1454352027.005966191]: No devices connected.... waiting for devices to be connected
process[camera/disparity_registered_hw-21]: started with pid [22247]
process[camera_base_link-22]: started with pid [22253]
process[camera_base_link1-23]: started with pid [22261]
process[camera_base_link2-24]: started with pid [22274]
process[camera_base_link3-25]: started with pid [22286]
process[rgbdslam-26]: started with pid [22301]
Initializing Node...
[ INFO] [1454352027.363848742]: Connected to roscore
[ INFO] [1454352027.776813671]: Using ORB keypoint detector.
[ INFO] [1454352027.776982264]: Using gridded keypoint detector with 3x3 cells, keeping 900 keypoints in total.
[ INFO] [1454352027.777047903]: Using adjusted keypoint detector with 5 maximum iterations, keeping the number of keypoints between 67 and 100
[ INFO] [1454352027.840839128]: Listening to /camera/rgb/image_color and /camera/depth_registered/sw_registered/image_rect_raw
[ INFO] [1454352030.007229077]: No devices connected.... waiting for devices to be connected
[ INFO] [1454352033.008288294]: No devices connected.... waiting for devices to be connected
[ INFO] [1454352036.008989125]: No devices connected.... waiting for devices to be connected

```

The kinect is listed in lsusb

```
$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 05c8:0379 Cheng Uei Precision Industry Co., Ltd (Foxlink) 
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. USB-2.0 4-Port HUB
Bus 001 Device 005: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
Bus 001 Device 018: ID 045e:02ae Microsoft Corp. Xbox NUI Camera
Bus 001 Device 016: ID 045e:02b0 Microsoft Corp. Xbox NUI Motor
Bus 001 Device 017: ID 045e:02ad Microsoft Corp. Xbox NUI Audio
Bus 001 Device 015: ID 0409:005a NEC Corp. HighSpeed Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

and the kinect works with the freenect library. What can I do to get the kinect working with rgbdslam w indigo?

**Comment by kbalisciano** [comment]
Just looking at it briefly you should try to launch your camera node and slam separately. You'd be better off using freenect instead of openni. Also use the regular gl-view test to test out the Kinect connection prior to trying it in ros. I ended up making my own launch file

**Comment by jacksonkr** [comment]
@kbalisciano regview works as well as the rest of the freenect demos. I'm not sure how to launch the camera node and slam separately. How I can accomplish that?

**Comment by kbalisciano** [comment]
Launch your freenect.launch file from your freenect package and separately launch your rgbdslam launch file which should be subscribed to the same topics as the freenect is publishing. You don't want to try to launch the openni launch file when using freenect

**Comment by jacksonkr** [comment]
@kbalisciano Worked like a charm, thanks for your wisdom.

```
$ roslaunch freenect_launch freenect.launch
$ roslaunch rgbdslam rgbdslam.launch
```

FYI for anyone else, this is Kinect 360 working on Ubuntu 14.04.05 via ROS indigo and rgbdslam_v2

**Comment by voyage19941119** [comment]
mine is worse ,  lsusb cannot find kinect ,but the light on kinect2 HUB is white(which means it is connected to the computer) . Do you have any idea ? I m confused

**Comment by jacksonkr** [comment]
@voyage19941119 
I hate to break it to you but that's more of a "noob" question. I sympathize though, because I was there once. It might be that you have a libusb version that doesn't work with your kinect. You'll have to trial & error quite a bit until you find the issue. Good luck and don't forget to use google a LOT until you get over this hurdle. That's what I did.

**Comment by voyage19941119** [comment]
sorry for the noob question～ First time using kinect ，thanks for helping though

**Comment by voyage19941119** [comment]
@jacksonkr 
thanks again for reply.Now rgbd can receive pictures from my kinect . But ,just two frams ,then it stucked


ros@ros-All-Series:~$ roslaunch rgbdslam openni+rgbdslam.launch 
... logging to /home/ros/.ros/log/cd92b358-3ed0-11e7-9065-9c5c8e7417d0/roslaunch-ros-All-Series-30627.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ros-All-Series:38589/

SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/depth_rectify_depth/interpolation: 0
 * /camera/depth_registered_rectify_depth/interpolation: 0
 * /camera/disparity_depth/max_range: 4.0
 * /camera/disparity_depth/min_range: 0.5
 * /camera/disparity_registered_hw/max_range: 4.0
 * /camera/disparity_registered_hw/min_range: 0.5
 * /camera/disparity_registered_sw/max_range: 4.0
 * /camera/disparity_registered_sw/min_range: 0.5
 * /camera/driver/depth_camera_info_url: 
 * /camera/driver/depth_frame_id: camera_depth_opti...
 * /camera/driver/depth_registration: False
 * /camera/driver/device_id: #1
 * /camera/driver/rgb_camera_info_url: 
 * /camera/driver/rgb_frame_id: camera_rgb_optica...
 * /rgbdslam/config/backend_solver: pcg
 * /rgbdslam/config/cloud_creation_skip_step: 2
 * /rgbdslam/config/cloud_display_type: POINTS
 * /rgbdslam/config/detector_grid_resolution: 3
 * /rgbdslam/config/feature_detector_type: ORB
 * /rgbdslam/config/feature_extractor_type: ORB
 * /rgbdslam/config/max_keypoints: 600
 * /rgbdslam/config/max_matches: 300
 * /rgbdslam/config/min_sampled_candidates: 4
 * /rgbdslam/config/neighbor_candidates: 4
 * /rgbdslam/config/optimizer_skip_step: 1
 * /rgbdslam/config/pose_relative_to: largest_loop
 * /rgbdslam/config/predecessor_candidates: 4
 * /rgbdslam/config/ransac_iterations: 100
 * /rgbdslam/config/topic_image_depth: /camera/depth_reg...
 * /rgbdslam/config/topic_image_mono: /camera/rgb/image...
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_hw_metric_rect (nodelet/nodelet)
    depth_registered_metric (nodelet/nodelet)
    depth_registered_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    disparity_depth (nodelet/nodelet)
    disparity_registered_hw (nodelet/nodelet)
    disparity_registered_sw (nodelet/nodelet)
    driver (nodelet/nodelet)
    ir_rectify_ir (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
    rgb_debayer (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
    rgb_rectify_mono (nodelet/nodelet)
  /
    camera_base_link (tf2_ros/static_transform_publisher)
    camera_base_link1 (tf2_ros/static_transform_publisher)
    camera_base_link2 (tf2_ros/static_transform_publisher)
    camera_base_link3 (tf2_ros/static_transform_publisher)
    rgbdslam (rgbdslam/rgbdslam)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[camera/camera_nodelet_manager-1]: started with pid [30645]
process[camera/driver-2]: started with pid [30646]
process[camera/rgb_debayer-3]: started with pid [30647]
process[camera/rgb_rectify_mono-4]: started with pid [30654]
process[camera/rgb_rectify_color-5]: started with pid [30657]
process[camera/ir_rectify_ir-6]: started with pid [30663]
process[camera/depth_rectify_depth-7]: started with pid [30685]
process[camera/depth_metric_rect-8]: started with pid [30699]
[ INFO] [1495445546.186406920]: Initializing nodelet with 4 worker threads.
process[camera/depth_metric-9]: started with pid [30705]
process[camera/depth_points-10]: started with pid [30726]
process[camera/register_depth_rgb-11]: started with pid [30743]
process[camera/points_xyzrgb_sw_registered-12]: started with pid [30756]
process[camera/depth_registered_sw_metric_rect-13]: started with pid [30758]
process[camera/depth_registered_rectify_depth-14]: started with pid [30760]
process[camera/points_xyzrgb_hw_registered-15]: started with pid [30762]
process[camera/depth_registered_hw_metric_rect-16]: started with pid [30764]
process[camera/depth_registered_metric-17]: started with pid [30767]
process[camera/disparity_depth-18]: started with pid [30768]
process[camera/disparity_registered_sw-19]: started with pid [30776]
process[camera/disparity_registered_hw-20]: started with pid [30781]
process[camera_base_link-21]: started with pid [30794]
process[camera_base_link1-22]: started with pid [30796]
process[camera_base_link2-23]: started with pid [30802]
process[camera_base_link3-24]: started with pid [30821]
process[rgbdslam-25]: started with pid [30824]
Initializing Node...
[ INFO] [1495445546.391886445]: Connected to roscore
[ INFO] [1495445546.547355159]: Using ORB keypoint detector.
[ INFO] [1495445546.547400990]: Using gridded keypoint detector with 3x3 cells, keeping 900 keypoints in total.
[ INFO] [1495445546.547422233]: Using adjusted keypoint detector with 5 maximum iterations, keeping the number of keypoints between 67 and 100
[ INFO] [1495445546.559440531]: Listening to /camera/rgb/image_color and /camera/depth_registered/sw_registered/image_rect_raw
[ INFO] [1495445546.987299038]: Number devices connected: 1
[ INFO] [1495445546.987366750]: 1. device on bus 003:33 is a SensorKinect (2bf) from PrimeSense (45e) with serial id '0000000000000000'
[ INFO] [1495445546.988004063]: Searching for device with index = 1
[ INFO] [1495445548.023178676]: Opened 'SensorKinect' on bus 3:33 with serial number '0000000000000000'
[ INFO] [1495445548.043286984]: rgb_frame_id = 'camera_rgb_optical_frame' 
[ INFO] [1495445548.043331903]: depth_frame_id = 'camera_depth_optical_frame' 
[ WARN] [1495445548.045897463]: Camera calibration file /home/ros/.ros/camera_info/rgb_0000000000000000.yaml not found.
[ WARN] [1495445548.045983213]: Using default parameters for RGB camera calibration.
[ WARN] [1495445548.046052566]: Camera calibration file /home/ros/.ros/camera_info/depth_0000000000000000.yaml not found.
[ WARN] [1495445548.046103473]: Using default parameters for IR camera calibration.
[ WARN] [1495445549.281150345]: First RGBD-Data Received
[ INFO] [1495445549.281569987]: Encoding: bgr8
Breaking detection iterations, because of missing depth[ INFO] [1495445549.314398409]: Feature 2d size: 580, 3D: 580
[ INFO] [1495445549.314433250]: Keypoints: 580
[ INFO] [1495445549.315419011]: Feature Count of Node:	580
[ WARN] [1495445549.325765042]: "openni_rgb_optical_frame" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1495445549.325809822]: Using Standard kinect /openni_camera -> /openni_rgb_optical_frame as transformation (This message is throttled to 1 per 5 seconds)
[ INFO] [1495445549.328708387]: Ground Truth Transform for First Node: Translation 0 0 0
[ INFO] [1495445549.328763625]: Ground Truth Transform for First Node: Rotation 0 0 0 1
[ INFO] [1495445549.328810734]: Adding initial node with id 0 and seq 0, v_id: 0
[ INFO] [1495445549.329036080]: Encoding: bgr8
[ INFO] [1495445549.329877369]: Setting Renderable
[ INFO] [1495445549.333865791]: No change to renderer skip (1).
[ INFO] [1495445549.334201918]: 1 Keyframes: 0, 
Breaking detection iterations, because of missing depth[ INFO] [1495445549.358166495]: Feature 2d size: 573, 3D: 573
[ INFO] [1495445549.358222004]: Keypoints: 573
[ INFO] [1495445549.358236537]: Feature Count of Node:	573
[ WARN] [1495445549.368386711]: "openni_rgb_optical_frame" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1495445549.368434152]: Using Standard kinect /openni_camera -> /openni_rgb_optical_frame as transformation (This message is throttled to 1 per 5 seconds)
[ INFO] [1495445549.370663114]: Node ID's to compare with candidate for node 1. Sequential: 0
[ INFO] [1495445549.371370329]: Nodes to compare: 0, 
[ INFO] [1495445549.371519002]: Running node comparisons in parallel in 3 (of 4) available threads
[ INFO] [1495445549.371846568]: Encoding: bgr8
[ INFO] [1495445549.371962504]: You specified FLANN with ORB, this is SLOW! Using BRUTEFORCE instead.
[ INFO] [1495445549.376750050]: My bruteforce Search runtime: 0.00472622 s
[ INFO] [1495445549.376969659]: 1 good iterations (from 100), inlier pct 91, inlier cnt: 273, error (MHD): 1.13
[ INFO] [1495445549.376991047]: Nodes 1<->0: 1 good iterations (from 100), inlier pct 91, inlier cnt: 273, error (MHD): 1.13
[ INFO] [1495445549.377009305]: RANSAC found a valid transformation with 273 inliers matches with average ratio 0.079393
[ INFO] [1495445549.377020397]: Returning Valid Edge
[ INFO] [1495445549.377296058]: Result of comparison 0: �I
[ INFO] [1495445549.377325086]: Rotation: 0.13, Distance:  0.005m
[ INFO] [1495445549.377338598]: Rotation: 0.13, Distance:  0.005m
[ INFO] [1495445549.377377421]: Added Edge between 0 and 1. Inliers: 273
[ INFO] [1495445549.377398923]: Adding node with id 1 and seq id 1 to the graph
[ INFO] [1495445549.377411011]: create cloud 1 1 0
Breaking detection iterations, because of missing depth[ INFO] [1495445549.386035377]: No change to renderer skip (1).
[ INFO] [1495445549.386309363]: Added Node, new graphsize: 2 nodes
[ WARN] [1495445549.386643355]: Loop Closures: 0, Sequential Edges: 1
[ WARN] [1495445549.386789540]: Starting Optimization
[ WARN] [1495445549.386946762]: Optimization with 2 cams, 140363088038528 nodes and 140363088022768 edges in the graph
[ INFO] [1495445549.387124749]: optimizeGraphImpl runtime: 0.00066005 s
[ INFO] [1495445549.387595121]: Added, Camera Pose Graph Size: 2N/1E, Duration: 0.015847, Inliers:  273
[ INFO] [1495445549.411392496]: Feature 2d size: 577, 3D: 577
[ INFO] [1495445549.411446797]: Keypoints: 577
[ INFO] [1495445549.411468281]: Feature Count of Node:	577
**[ WARN] [1495445549.421614344]: "openni_rgb_optical_frame" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1495445549.421650997]: Using Standard kinect /openni_camera -> /openni_rgb_optical_frame as transformation (This message is throttled to 1 per 5 seconds)**
[ INFO] [1495445549.423788512]: Node ID's to compare with candidate for node 2. Sequential: 0, 1
[ INFO] [1495445549.424035732]: Nodes to compare: 1, 0, 
[ INFO] [1495445549.424325088]: Running node comparisons in parallel in 3 (of 4) available threads
[ INFO] [1495445549.424486104]: You specified FLANN with ORB, this is SLOW! Using BRUTEFORCE instead.
[ INFO] [1495445549.429217194]: My bruteforce Search runtime: 0.00465879 s
[ INFO] [1495445549.429417132]: 1 good iterations (from 100), inlier pct 98, inlier cnt: 295, error (MHD): 0.72
[ INFO] [1495445549.429446119]: Nodes 2<->1: 1 good iterations (from 100), inlier pct 98, inlier cnt: 295, error (MHD): 0.72
[ INFO] [1495445549.429460902]: RANSAC found a valid transformation with 295 inliers matches with average ratio 0.070426
[ INFO] [1495445549.429471305]: Returning Valid Edge
[ INFO] [1495445549.429499421]: You specified FLANN with ORB, this is SLOW! Using BRUTEFORCE instead.
[ INFO] [1495445549.431781479]: Encoding: bgr8
Breaking detection iterations, because of missing depth[ INFO] [1495445549.439791583]: My bruteforce Search runtime: 0.0102416 s
[ INFO] [1495445549.440017631]: 1 good iterations (from 100), inlier pct 86, inlier cnt: 260, error (MHD): 1.98
[ INFO] [1495445549.440049425]: Nodes 2<->0: 1 good iterations (from 100), inlier pct 86, inlier cnt: 260, error (MHD): 1.98
[ INFO] [1495445549.440070438]: RANSAC found a valid transformation with 260 inliers matches with average ratio 0.074407
[ INFO] [1495445549.440080627]: Returning Valid Edge
[ INFO] [1495445549.440119999]: Result of comparison 0: 08
[ INFO] [1495445549.440137911]: Rotation: 1.43, Distance:  0.050m
[ INFO] [1495445549.440158322]: Rotation: 1.43, Distance:  0.050m
[ INFO] [1495445549.443106606]: Feature 2d size: 578, 3D: 578
[ INFO] [1495445549.443135825]: Keypoints: 578
[ INFO] [1495445549.443158478]: Feature Count of Node:	578
**[ WARN] [1495445549.453348471]: "openni_rgb_optical_frame" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1495445549.453373741]: Using Standard kinect /openni_camera -> /openni_rgb_optical_frame as transformation (This message is throttled to 1 per 5 seconds)**


I really have no idea about this after googling a lot ~

Have you changed the input topic value in rgbdslam.launch or openni+rgbdslam.launch?

**Comment by jacksonkr** [comment]
@voyage19941119 I'll reach out to you separately as this is getting away from the original topic.
